-- Crear la base de datos
-- reemplazar el usuario para ejecutar este comando 
psql -U [usuario] -c "CREATE DATABASE prueba_tata;"




-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public.cliente_cliente_id_seq;

CREATE SEQUENCE public.cliente_cliente_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.cuenta_cuenta_id_seq;

CREATE SEQUENCE public.cuenta_cuenta_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.movimiento_movimiento_id_seq;

CREATE SEQUENCE public.movimiento_movimiento_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.persona_persona_id_seq;

CREATE SEQUENCE public.persona_persona_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.cuenta definition

-- Drop table

-- DROP TABLE public.cuenta;

CREATE TABLE public.cuenta (
	cuenta_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cliente_id int8 NULL,
	estado bool NULL,
	numero_cuenta varchar(255) NULL,
	saldo_inicial numeric(38, 2) NULL,
	tipo_cuenta varchar(255) NULL,
	CONSTRAINT cuenta_pkey PRIMARY KEY (cuenta_id)
);


-- public.persona definition

-- Drop table

-- DROP TABLE public.persona;

CREATE TABLE public.persona (
	persona_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	direccion varchar(255) NULL,
	edad int4 NOT NULL,
	genero varchar(255) NULL,
	identificacion varchar(255) NULL,
	nombre varchar(255) NULL,
	telefono varchar(255) NULL,
	CONSTRAINT persona_pkey PRIMARY KEY (persona_id)
);


-- public.cliente definition

-- Drop table

-- DROP TABLE public.cliente;

CREATE TABLE public.cliente (
	cliente_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	contrasenia varchar(255) NULL,
	estado bool NULL,
	persona_id int8 NULL,
	CONSTRAINT cliente_pkey PRIMARY KEY (cliente_id),
	CONSTRAINT ukfp4oq6jpmv4n8xirq1dt5910b UNIQUE (persona_id),
	CONSTRAINT fkmc52upywn8gona2iiwwwphb92 FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id)
);


-- public.movimiento definition

-- Drop table

-- DROP TABLE public.movimiento;

CREATE TABLE public.movimiento (
	movimiento_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	fecha timestamp(6) NOT NULL,
	saldo numeric(38, 2) NULL,
	tipo_movimiento varchar(255) NULL,
	valor numeric(38, 2) NULL,
	cuenta_id int8 NULL,
	CONSTRAINT movimiento_pkey PRIMARY KEY (movimiento_id),
	CONSTRAINT fk4ea11fe7p3xa1kwwmdgi9f2fi FOREIGN KEY (cuenta_id) REFERENCES public.cuenta(cuenta_id)
);
